---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: pip
    directories:
    - "/translator"
    - "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: docker
    directories:
      - "/compose/local/"
      - "/compose/production"
    schedule:
      interval: "weekly"
