include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Code-Quality.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml

stages:
- lint
- pytest
# Run code quality and other stuff later
- test

variables:
  POSTGRES_USER: scram
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: test_scram
  POSTGRES_HOST_AUTH_METHOD: trust

flake8:
  stage: lint
  image: python:3.8-alpine
  before_script:
  - ./.ci-scripts/flake8_before.sh
  script:
  - ./.ci-scripts/flake8_run.sh

pytest:
  stage: pytest
  image: docker:24.0.6-dind
  services:
  - docker:dind
  before_script:
    - ./.ci-scripts/pytest_before.sh
  script:
    - ./.ci-scripts/pytest_run.sh
  after_script:
    - ./.ci-scripts/pytest_after.sh
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

gemnasium-dependency_scanning:
  variables:
    PIP_REQUIREMENTS_FILE: requirements/base.txt

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths:
    - gl-code-quality-report.html

sast:
  stage: test
